apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: akri-helmrelease
  namespace: default
spec:
  releaseName: akri-dev
  chart:
    spec:
      chart: akri 
      version: akri-0.8.23 # or arm64
      sourceRef:
        kind: HelmRepository
        name: my-repository
        namespace: default
      values:
        opcua:
          discovery.enabled: true
          configuration:
            enabled: true 
            name: akri-monitor 
            brokerPod.image.repository: "ghcr.io/project-akri/akri/opcua-monitoring-broker"
            brokerProperties.IDENTIFIER: 'Thermometer_Temperature'
            brokerProperties.NAMESPACE_INDEX: '2'
            discoveryDetails.discoveryUrls[0]: "opc.tcp://10.0.8.51:62541"
  interval: 30m